### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by ericpre** [nion-software/eels-analysis#44]
As for other plugins `nionswift-eels-analysis` should be available on conda-forge.

**Comment by cmeyer** [comment]
I'll add this. Thanks. I'm not sure why I skipped it during the first round.

**Comment by ericpre** [comment]
When I made the packages for conda-forge in https://github.com/conda-forge/staged-recipes/pull/10583, there was no license as mentioned in https://github.com/nion-software/eels-analysis/issues/34, therefore I couldn't make the package because conda-forge doesn't allow distributing software without compatible licence...

**Comment by cmeyer** [comment]
PR https://github.com/conda-forge/staged-recipes/pull/12853

Please note that EELS analysis is less mature than other packages and still evolving over the next several weeks. Background subtraction is more stable, while elemental analysis will get a full rewrite.

**Comment by cmeyer** [comment]
Closed. https://anaconda.org/conda-forge/nionswift-eels-analysis
